<?php
require __DIR__ . '/data/pets.php';
$page = 'home';
function petCard(array $pet): string {
    $traits = htmlspecialchars($pet['breed'] . ' · ' . $pet['age'], ENT_QUOTES, 'UTF-8');
    $name = htmlspecialchars($pet['name'], ENT_QUOTES, 'UTF-8');
    $species = htmlspecialchars($pet['species'], ENT_QUOTES, 'UTF-8');
    $status = htmlspecialchars($pet['status'], ENT_QUOTES, 'UTF-8');
    $location = htmlspecialchars($pet['location'], ENT_QUOTES, 'UTF-8');
    $image = htmlspecialchars($pet['image'], ENT_QUOTES, 'UTF-8');
    return '<article class="pet-card"><img src="' . $image . '" alt="' . $name . ', ' . $traits . '"><div class="pet-body"><div class="pet-topline"><span>' . $species . '</span><span>' . $status . '</span></div><div class="pet-bottom"><h3>' . $name . '</h3><button class="heart" data-favorite="' . $pet['id'] . '" aria-label="Save ' . $name . '">♡</button></div><p class="pet-breed">' . $traits . '</p><p class="pet-location">⌖ ' . $location . '</p><div class="pet-bottom"><span class="fee">$' . $pet['fee'] . ' adoption fee</span><a class="button button-light" href="pet.php?id=' . $pet['id'] . '">Meet ' . $name . '</a></div></div></article>';
}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Paw &amp; Home | Field notes for good homes</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700;800;900&family=Quicksand:wght@500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="css/styles.css"></head><body><?php require __DIR__ . '/includes/header.php'; ?><main class="page-shell"><section class="hero"><div class="hero-copy"><span class="kicker">A better beginning / 001</span><h1>Find the one who feels like home.</h1><p>Meet pets from thoughtful caregivers and local rescue partners. Browse gently, ask questions, and make room for a new kind of love.</p><div class="hero-actions"><a class="button button-dark" href="pets.php">Find a pet</a><a class="button button-light" href="rehome.php">Rehome a pet</a></div></div><div class="hero-art"><img src="https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=1000&q=85" alt="Happy dog outdoors"><div class="art-note"><strong>18 / open doors</strong> loving pets looking for their next chapter</div></div></section><section class="manifesto"><article><b>01</b><h3>Start with connection.</h3><p>Every profile shares personality, needs, and the little details that matter.</p></article><article><b>02</b><h3>Local by design.</h3><p>Meet people and pets in your area before taking the next step.</p></article><article><b>03</b><h3>Thoughtful matches.</h3><p>Take your time. The best home is the one that fits both of you.</p></article></section><div class="section-header"><div><span class="kicker">Dispatch / current residents</span><h2>Pets waiting for you</h2></div><a href="pets.php">See all pets →</a></div><section class="pet-grid"><?php foreach (array_slice($pets, 0, 3) as $pet) echo petCard($pet); ?></section></main><script>window.PETS = <?= json_encode($pets, JSON_UNESCAPED_SLASHES) ?>;</script><script src="src/js/app.js"></script></body></html>
